variables:
  WERF_VERSION: "1.1 stable"
  WERF_STAGES_STORAGE: ":local"

stages:
  - test
  - build
  - deploy

test:
  script:
    - docker run --rm -v "$(pwd):/app" -w /app maven:3-jdk-8 mvn checkstyle:checkstyle
  stage: test
  tags:
    - werf

Build:
  stage: build
  script:
    - type multiwerf && source <(multiwerf use ${WERF_VERSION})
    - type werf && source <(werf ci-env gitlab --verbose)
    - werf build-and-publish
  tags:
    - werf

.base_deploy: &base_deploy 
 stage: deploy 
 script: 
   - echo ${CI_ENVIRONMENT_URL} | cut -d / -f 3 
   - type multiwerf && source <(multiwerf use ${WERF_VERSION}) 
   - type werf && source <(werf ci-env gitlab --verbose) 
   - werf helm repo init
   - werf helm dependency update
   - werf deploy --stages-storage :local 
     --namespace ${CI_NAMESPACE} 
     --set "global.ci_url=$(echo ${CI_ENVIRONMENT_URL} | cut -d / -f 3)" 
     --set "global.env=${CI_ENVIRONMENT_SLUG}" 
     --timeout ${CI_TIMEOUT:-10800} 
 except: 
   - schedules 
 tags: 
   - werf

Deploy to Stage:
  extends: .base_deploy
  stage: deploy
  environment:
    name: stage
    url: http://stage.example.com
  except:
    - schedules
  only:
    - merge_requests
    - master
  when: manual

Deploy to Production:
  extends: .base_deploy
  stage: deploy
  environment:
    name: production
    url: http://example.com
  except:
    - schedules
  only:
    - merge_requests
    - master
  when: manual

