apiVersion: batch/v1
kind: Job
metadata:
  name: "migrate-db"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: migrate-db
        image: {{ .Values.werf.image.backend }}
        command:
        - sh
        - -euc
        - |
          is_mysql_available() {
            tries=$1
            i=0
            while [ $i -lt $tries ]; do
              mysqladmin -h $DB_HOST -P 3306 -u $DB_USERNAME -p$DB_PASSWORD ping || return 1
              i=$((i+1))
              sleep 1
            done
          }

          # [<ru>] Дождёмся, когда `mysqladmin ping` отработает 10 раз подряд.
          until is_mysql_available 10; do
            sleep 1
          done

          # [<ru>] Выполним миграции.
          php artisan migrate --force
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          value: werf-guide-app
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: password
