version: "3.9"

services:
  site:
    image: $WERF_WEB_BACKEND_DOCKER_IMAGE_NAME
    command: "/app/server"
    environment:
      WERF_LOG_VERBOSE: "on"
      LOG_LEVEL: "trace"
    volumes:
      - ".helm/multiwerf-dev.json:/app/multiwerf/multiwerf.json:ro"
      - ".helm/trdl_channels-dev.yaml:/app/trdl/trdl_channels.yaml:ro"

  tuf:
    image: $WERF_TUF_ROUTER_DOCKER_IMAGE_NAME
    command: ["nginx", "-g", "daemon off;"]

  front:
    image: nginx:latest
    volumes:
      - ".werf/nginx-dev-slow.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - site
      - tuf

