company_name: Flant
company_url: https://flant.ru
url: https://werf.io
site_lang: en
baseurl: /applications_guide_en
docsurl: https://werf.io

exclude:
- applications_guide_ru/

include:
- applications_guide_en/

breadcrumbs:
  hometext: "Home"

