apiVersion: apps/v1
kind: Deployment
metadata:
  name: werf-guide-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: werf-guide-app
  template:
    metadata:
      labels:
        app: werf-guide-app
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        # [<en>] Задаем переменную окружения, переводящую Gin в Release Mode.
        # [<ru>] Задаем переменную окружения, переводящую Gin в Release Mode.
        # [<snippet log_env>]
        env:
          - name: GIN_MODE
            value: "release"
        # [<endsnippet log_env>]
        ports:
        - containerPort: 8080
