@startuml

package "Deployment" {
  node "node-assets" {
    [nginx]
  }

  node "basicapp" {
    [node]
  }

}

package "Configmap" {
  [basicapp-configmap]
}

[Ingress] --> [nginx]
[nginx] --> [node]
[nginx] - [basicapp-configmap]

@enduml
