spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${SQLITE_FILE}
    username:
    password:
  jpa:
    database-platform: com.example.demo.data.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true