#!/bin/bash

export WERF_BUILDAH_MODE=native-chroot
export WERF_INSECURE_REGISTRY=1
export WERF_FORCE_STAGED_DOCKERFILE=1
export WERF_SKIP_TLS_VERIFY_REGISTRY=1
export WERF_DISABLE_AUTO_HOST_CLEANUP=1
export WERF_BUNDLE_INSECURE_REGISTRY=1
export WERF_BUNDLE_SKIP_TLS_VERIFY_REGISTRY=1
export WERF_LOG_TERMINAL_WIDTH=100

export CACHE_VERSION=1
