---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:9.1
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: db-envs
          - secretRef:
              name: db-envs
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
# [<snippet volume_claim_templates>]
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "{{ .Values.mysql.storageSize }}"
# [<endsnippet volume_claim_templates>]
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
