apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapp
spec:
  selector:
    matchLabels:
      app: basicapp
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: basicapp
        command: ["node","/app/app.js"]
        image: {{ tuple "basicapp" . | werf_image}}
        workingDir: /app
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: "POSTGRESQL_HOST"
            value: "mydomain.io"
          - name: "POSTGRESQL_PORT"
            value: "5432"
          - name: "POSTGRESQL_DB"
            value: "postgres"
          - name: "POSTGRESQL_USER"
            value: "postgres"
          - name: "POSTGRESQL_PASSWORD"
            value: "mysecretpassword"
