apiVersion: v1
kind: Secret
metadata:
  name: db-envs
type: Opaque
data:
  {{- range $key, $val := .Values.mysql.secretEnvs }}
  "{{ $key }}": "{{ $val | b64enc }}"
  {{- end }}
  {{- range $key, $val := .Values.mysql.envs }}
  "{{ $key }}": "{{ $val | b64enc }}"
  {{- end }}
