dependencies:
  - name: backend
    version: "1.0.0"
    export-values:
      - parent: werf
        child: werf

  - name: frontend
    version: "1.0.0"
    export-values:
      - parent: werf
        child: werf
