apiVersion: batch/v1
kind: Job
metadata:
  # [<ru>] Версия Helm-релиза в имени Job заставит Job каждый раз пересоздаваться.
  # [<ru>] Так мы сможем обойти то, что Job неизменяема.
  name: "setup-and-migrate-db-rev{{ .Release.Revision }}"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: setup-and-migrate-db
        image: {{ .Values.werf.image.backend }}
        command:
        - sh
        - -euc
        - |
          is_mysql_available() {
            tries=$1
            i=0
            while [ $i -lt $tries ]; do
              mysqladmin -h mysql -P 3306 -u root -p=password ping || return 1
              i=$((i+1))
              sleep 1
            done
          }

          # [<ru>] Дождёмся, когда `mysqladmin ping` отработает 10 раз подряд.
          until is_mysql_available 10; do
            sleep 1
          done

          # [<ru>] Выполним первоначальную настройку базы, если она не выполнена, а иначе выполним миграции.
          bundle exec rails db:prepare
        env:
        - name: RAILS_ENV
          value: production
