FROM node:14-stretch as asset-builder
WORKDIR /app
COPY frontend/ .
RUN apt update
RUN apt install -y build-essential tzdata locales
RUN cd /app
RUN npm i
RUN ls -la
RUN cat package.json
RUN npm run build

###################################

FROM nginx:stable-alpine
COPY .werf/nginx.conf /etc/nginx/nginx.conf
COPY --from=asset-builder /app/dist /www
