apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    "werf.io/set-replicas-only-on-creation": "true"
  labels:
    service: {{ .Chart.Name }}
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      service: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: github-werfio
      containers:
        - name: web
          command: ["nginx", "-g", "daemon off;"]
          image: {{ tuple "frontend" . | werf_image }}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    service: {{ .Chart.Name }}
  ports:
  - name: http
    port: 80
    protocol: TCP
{{- if ne .Values.global.env "production" }}
{{- end }}
