{{- $host := pluck .Values.werf.env .Values.host | first | default .Values.host._default  }}
{{- if  hasPrefix "review" .Values.werf.env }}
{{- $host = ( printf "%s.%s" .Values.werf.env (pluck "dev" .Values.host | first | default .Values.host._default ) | lower ) }}
{{- end }}
{{- $targetCluster := include "targetCluster" . }}
{{- $ruHost := printf "ru.%s" $host }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuf-router
  annotations: {}
spec:
  ingressClassName: {{ include "ingressClassName" . }}
  tls:
  - hosts:
{{- if eq .Values.werf.env "production" }}
{{- if eq $targetCluster "ru" }}
      - {{ $ruHost }}
{{- else }}
      - {{ $host }}
{{- end }}
    secretName: tls-{{ $host }}
{{- else }}
      - {{ $host }}
      - ru-{{ $host }}
    secretName: {{ pluck .Values.werf.env .Values.ingressSecretName | first | default .Values.ingressSecretName._default }}
{{- end }}
  rules:
{{- if or (ne .Values.werf.env "production") (eq $targetCluster "eu") }}
  - host: {{ $host }}
    http:
      paths:
      - path: /targets/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- end }}
{{- if eq .Values.werf.env "production" }}
{{- if eq $targetCluster "ru" }}
  - host: {{ $ruHost }}
    http:
      paths:
      - path: /targets/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- end }}
{{- else }}
  - host: ru-{{ $host }}
    http:
      paths:
      - path: /targets/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- end }}
