{{- $host := pluck .Values.global.env .Values.host | first | default .Values.host._default  }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Original-URI         $request_uri;
      ssi on;
      ssi_silent_errors on;
{{- if eq .Values.global.env "production" }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
{{- end }}
{{- if ne .Values.global.env "production" }}
    nginx.ingress.kubernetes.io/auth-url: http://basic-auth.kube-basic-auth.svc.cluster.local/werfio
{{- end }}
spec:
  tls:
  - hosts:
      - {{ $host }}
      - ru.{{ $host }}
{{- if eq .Values.global.env "production" }}
      - www.{{ $host }}
{{- end }}
    secretName: tls-{{ $host }}
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /guides
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
  - host: ru.{{ $host }}
    http:
      paths:
      - path: /guides
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
---
