{{- $host := pluck .Values.werf.env .Values.host | first | default .Values.host._default  }}
{{- $ingressSecretName := pluck .Values.werf.env .Values.ingressSecretName | first | default .Values.ingressSecretName._default }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuf-router
  annotations: {}
spec:
  ingressClassName: {{ include "ingressClassName" . }}
  tls:
  - hosts:
      - {{ $host }}
{{- if eq .Values.werf.env "production" }}
      - ru.{{ $host }}
    secretName: {{ $ingressSecretName }}
{{- else }}
      - ru-{{ $host }}
    secretName: {{ $ingressSecretName }}
{{- end }}
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /targets/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- if eq .Values.werf.env "production" }}
  - host: ru.{{ $host }}
    http:
      paths:
      - path: /targets/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- else }}
  - host: ru-{{ $host }}
    http:
      paths:
      - path: /targets/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download/
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- end }}
