global:
  targetCluster: ""

imagePullSecrets:
  - github-werfio

clusters:
  eu:
    placement:
      nodeSelector: {}
      tolerations: []
      affinity: {}
  ru:
    placement:
      nodeSelector: {}
      tolerations: []
      affinity: {}

priorityClassName:
  _default: develop
  production: production-medium
host:
  production: werf.io
  test: werf.test.flant.dev
  _default: werf.test.flant.dev

ingressClassName:
  _default: "nginx"
  production: "standalone-geo"


ingressSecretName:
  _default: wildcard-dev-flant-dev
  test: wildcard-test-flant-dev
  production: tls-werf-io

resources:
  requests:
    memory:
      _default: 30M
      production: 300M
  limits:
    memory:
      _default: 30M
      production: 300M

docs:
  currentRoot: v2
  supportedRoots:
    - v3
    - v2
    - v1.2
  latestAliasEnabled: true

backend:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                service: backend
