name: Deploy

on:
  push:
    branches:
      - chore/docs-major-routing
  pull_request:
    types: [labeled, synchronize]
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: "Target environment in dev cluster"
        required: true
        default: test
        type: choice
        options:
          - test
          - stage

env:
  WERF_ENV: "production"
  WERF_REPO: "ghcr.io/${{ github.repository_owner }}/werfio-guides"
  WERF_STAGES_STORAGE: "ghcr.io/werf/werfio-guides-stages"
  WERFIO_GITHUB_TOKEN: "${{ secrets.API_TOKEN }}"

jobs:
  converge:
    name: Deploy
    if: >-
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      (contains(github.event.pull_request.labels.*.name, 'test website') ||
      contains(github.event.pull_request.labels.*.name, 'stage website')))
    runs-on: prod-github-runner-0
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v2

      - name: Deploy to test
        if: >-
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.targetEnvironment == 'test') ||
          (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'test website'))
        run: |
          . $(werf ci-env github --as-file)
          werf converge
        env:
          WERF_NAMESPACE: "werfio-test"
          WERF_RELEASE: "werfio-site-test"
          WERF_LOG_VERBOSE: "on"
          WERF_ENV: "test"
          WERF_KUBE_CONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64_DEV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to stage
        if: >-
          (github.event_name == 'workflow_dispatch' && github.event.inputs.targetEnvironment == 'stage') ||
          (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'stage website'))
        run: |
          . $(werf ci-env github --as-file)
          werf converge
        env:
          WERF_NAMESPACE: "werfio-stage"
          WERF_RELEASE: "werfio-site-stage"
          WERF_LOG_VERBOSE: "on"
          WERF_ENV: "stage"
          WERF_KUBE_CONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64_DEV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notification:
    name: Notification
    if: always()
    needs: converge
    uses: werf/common-ci/.github/workflows/notification.yml@main
    secrets:
      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
