name: Validation

on:
  push:
    paths:
      - '**/*.md'
      - '**/*.html'

jobs:
  checkk_links:
    container: jekyll/builder:3
    name: Check broken links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: [ru, en]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare environment
      run: |
        cd common
        apk add --update nodejs npm
        chmod 777 Gemfile.lock
        mkdir -pm 777 js css fonts
        gem update bundler
        bundle install
        npm install

    - name: Build (ru)
      if: matrix.lang == 'ru'
      run: |
        cd ru.werf.io/guides
        mkdir -pm 777 .jekyll-cache _site
        npm run prod:webpack
        npm run prod:jekyll

    - name: Build (en)
      if: matrix.lang == 'en'
      run: |
        cd werf.io/guides
        mkdir -pm 777 .jekyll-cache _site
        npm run prod:webpack
        npm run prod:jekyll

    - name: Check links
      if: matrix.lang == 'en'
      run: |
        cd werf.io/guides
        ln -s ./ _site/guides
        bundle exec htmlproofer \
          --allow-hash-href \
          --empty-alt-ignore \
          --check_html \
          --file_ignore "/____________/" \
          --url_ignore "/localhost/,/t.me/,/slack.com/,/cncf.io/,/example.com/,/github.com\/werf\/werf-guides\/edit/,/apple-touch-icon.png/,/site.webmanifest/,/favicon/,/safari-pinned-tab/" \
          --url-swap "^\/documentation/:https\://werf.io/documentation/" \
          --http-status-ignore 0 \
          ./_site/

    - name: Check links
      if: matrix.lang == 'ru'
      run: |
        cd ru.werf.io/guides
        ln -s ./ _site/guides
        bundle exec htmlproofer \
          --allow-hash-href \
          --empty-alt-ignore \
          --check_html \
          --file_ignore "/____________/" \
          --url_ignore "/localhost/,/t.me/,/slack.com/,/cncf.io/,/example.com/,/github.com\/werf\/werf-guides\/edit/,/apple-touch-icon.png/,/site.webmanifest/,/favicon/,/safari-pinned-tab/" \
          --url-swap "^\/documentation/:https\://ru.werf.io/documentation/" \
          --http-status-ignore 0 \
          ./_site/
