name: Converge guides on Test

on:
  pull_request:
    types: [labeled, synchronize]
  
jobs:
  unlabel:
    name: Converge to Test
    if: github.event.label.name == 'test guides' || contains( github.event.pull_request.labels.*.name, 'test guides' )
    runs-on: self-hosted
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Deploy website to test
      uses: werf/actions/converge@v1.2
      with:
        env: test
      env:
        WERF_KUBE_CONTEXT: dev
        WERF_LOG_VERBOSE: "on"
        WERF_NAMESPACE: "werfio-test"
        WERF_STAGES_STORAGE: docker.pkg.github.com/${{ github.repository }}/stages-guides
